// BGEE

ACTION_IF GAME_IS ~bgee~ BEGIN
COPY  ~Eldritch_Magic/Effects/emlaw.eff~   ~override~
COPY ~Eldritch_Magic/ITM/emsw1h05.itm~ ~override~ // Silver Long Sword +2
  SAY NAME1 ~~
  SAY NAME2 @102
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @103
COPY ~Eldritch_Magic/ITM/emsw1h06.itm~ ~override~ // Flaming Burst Long Sword +1
  SAY NAME1 ~~
  SAY NAME2 @104
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @105
COPY ~Eldritch_Magic/ITM/emsw1h07.itm~ ~override~ // Frost-Fire Long Sword +2
  SAY NAME1 ~~
  SAY NAME2 @106
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @107
COPY ~Eldritch_Magic/ITM/emsw1h10.itm~ ~override~ // Mithral Long Sword +3
  SAY NAME1 ~~
  SAY NAME2 @108
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @109
COPY ~Eldritch_Magic/ITM/emsw1h02.itm~ ~override~ // Adamantine Long Sword of Biting +1
  SAY NAME1 ~~
  SAY NAME2 @110
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @111
COPY ~Eldritch_Magic/ITM/emsw1h12.itm~ ~override~ // Vampiric Short Sword +1
  SAY NAME1 ~~
  SAY NAME2 @112
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @113
COPY ~Eldritch_Magic/ITM/emsw1h03.itm~ ~override~ // Masterwork Cold Iron Long Sword
  SAY NAME1 ~~
  SAY NAME2 @114
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @115
COPY ~Eldritch_Magic/ITM/emsw1h13.itm~ ~override~ // Elemental Long Sword +1
  SAY NAME1 ~~
  SAY NAME2 @116
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @117
COPY ~Eldritch_Magic/ITM/emsw1h09.itm~ ~override~ // Holy Avenger Long Sword +3
  SAY NAME1 ~~
  SAY NAME2 @118
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @119
COPY ~Eldritch_Magic/ITM/embhaal.itm~ ~override~ // Bhaal's Holy Symbol
  SAY NAME1 ~~
  SAY NAME2 @120
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @121
COPY ~Eldritch_Magic/ITM/emchanco.itm~ ~override~ // Elven Chain Mail of the Collector
  SAY NAME1 ~~
  SAY NAME2 @140
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @141
// BG2EE- Won't appear in BGEE
COPY  ~Eldritch_Magic/Spells/emcdcha.spl~   ~override~
      SAY 0xfe @219 //You feel a tug from the Pocket Plane as an artifact lost to time materializes among your possessions. Surely such a happening is linked to your powerful heritage.
COPY  ~Eldritch_Magic/Spells/emcdbls.spl~   ~override~
      SAY 0x15e @213 //You have been acknowledged by the Bladesinger's Guild.
COPY  ~Eldritch_Magic/Spells/emcdsw1.spl~   ~override~
      SAY 0xfe @214 //You are an exemplary Bladesinger and a hero among elves. The Gods themselves have taken notice of your righteous fury and now the Seldarine have blessed you with the tool to exact it. Be advised not to abuse a divine gift.
COPY  ~Eldritch_Magic/Effects/emundead.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emdemon.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh1.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh2.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh3.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/em2d6.eff~   ~override~
COPY  ~Eldritch_Magic/Spells/emsare1.spl~   ~override~
      SAY 0xce @94 //Blades
COPY  ~Eldritch_Magic/Spells/emsare2.spl~   ~override~
      SAY 0xce @95 //Spikes
COPY  ~Eldritch_Magic/Dialog/emsw1h01.dlg~   ~override~
      SAY 0x34  @200
      SAY 0x44  @201
      SAY 0x54  @202
      SAY 0x64  @204
      SAY 0x74  @206
      SAY 0x84  @208
      SAY 0x98  @198
      SAY 0xb8  @199
      SAY 0xd8  @203
      SAY 0xf8  @205
      SAY 0x118 @207
COPY_EXISTING ~lunumab.2da~ ~override~
  APPEND ITEMDIAL.2da ~EMSW1H01      5689   EMSW1H01~
COPY_EXISTING ~item_use.2da~ ~override~
  APPEND item_use.2da ~emplat01   SAREVOK    9382       2~
  APPEND item_use.2da ~emsw2h01   SAREVOK    9382       2~
  APPEND item_use.2da ~emsarev   SAREVOK    9382       2~
COPY ~Eldritch_Magic/ITM/emboot01.itm~ ~override~ // Elven Boots of Speed: The Paws of the Lythari
  SAY NAME1 @26
  SAY NAME2 @27
  SAY UNIDENTIFIED_DESC @28
  SAY DESC @29
  SAY 0x15e @96
COPY ~Eldritch_Magic/ITM/emchan01.itm~ ~override~ // Holy Elven Chain +6
  SAY NAME1 @30
  SAY NAME2 @31
  SAY UNIDENTIFIED_DESC @32
  SAY DESC @33
  SAY 0x3fe @96
COPY ~Eldritch_Magic/ITM/emclck01.itm~ ~override~ // Bladesinger's Shroud
  SAY NAME1 @34
  SAY NAME2 @35
  SAY UNIDENTIFIED_DESC @36
  SAY DESC @37
  SAY 0x2b6 @96
COPY ~Eldritch_Magic/ITM/emring01.itm~ ~override~ // Bladesinger's Signet
  SAY NAME1 @38
  SAY NAME2 @39
  SAY UNIDENTIFIED_DESC @40
  SAY DESC @41
  SAY 0x2de @96
COPY ~Eldritch_Magic/BAM/emsw1h01.bam~ ~override~
COPY ~Eldritch_Magic/ITM/emsw1h01.itm~ ~override~// Seldarine's Fury +6: Shame of the Gods
  SAY NAME1 @42
  SAY NAME2 @43
  SAY UNIDENTIFIED_DESC @44
  SAY DESC @45
  SAY 0x586 @96
COPY ~Eldritch_Magic/ITM/emsw1h11.itm~ ~override~ // Angharradh's Song
  SAY NAME1 ~~
  SAY NAME2 @47
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @49
  SAY 0x1f6 @96
COPY ~Eldritch_Magic/ITM/embelt25.itm~ ~override~ // Girdle of Titan Strength
  SAY NAME1 ~~
  SAY NAME2 @58
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @59
COPY ~Eldritch_Magic/ITM/emthay.itm~ ~override~ // Red Robe of Thay
  SAY NAME1 ~~
  SAY NAME2 @60
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @61
  SAY 0x36e @97
COPY ~Eldritch_Magic/ITM/emsw1h04.itm~ ~override~ // Blue Flame Taragarth +3
  SAY NAME1 ~~
  SAY NAME2 @62
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @63
COPY ~Eldritch_Magic/ITM/emdagg01.itm~ ~override~ // Netherese Spellblade
  SAY NAME1 ~~
  SAY NAME2 @64
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @65
COPY ~Eldritch_Magic/ITM/emsw1h08.itm~ ~override~ // Plasma Blade of Kossuth: Igneus Nova
  SAY NAME1 ~~
  SAY NAME2 @66
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @67
COPY ~Eldritch_Magic/BAM/phelm29.bmp~ ~override~
COPY ~Eldritch_Magic/ITM/empsion.itm~ ~override~ // Drow Psionicist's Cowl
  SAY NAME1 ~~
  SAY NAME2 @68
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @69
COPY ~Eldritch_Magic/ITM/emveye.itm~ ~override~ // Eye of Vecna
  SAY NAME1 ~~
  SAY NAME2 @70
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @71
COPY ~Eldritch_Magic/ITM/emvhand.itm~ ~override~ // Hand of Vecna
  SAY NAME1 ~~
  SAY NAME2 @72
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @73
// COPY ~Eldritch_Magic/ITM/emcesp01.itm~ ~override~ // Claw of Kazgaroth
//  SAY NAME1 ~~
//  SAY NAME2 @50
//  SAY UNIDENTIFIED_DESC ~~
//  SAY DESC @51
COPY ~Eldritch_Magic/ITM/emimoen.itm~ ~override~ // Imoen's Belt
  SAY NAME1 ~~
  SAY NAME2 @52
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @53
  SAY 0x2de @98
COPY ~Eldritch_Magic/ITM/emplat01.itm~ ~override~ // Sarevok's Bladed Armor +5
  SAY NAME1 ~~
  SAY NAME2 @54
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @55
COPY ~Eldritch_Magic/ITM/emsw2h01.itm~ ~override~ // Sword of Chaos +5
  SAY NAME1 ~~
  SAY NAME2 @56
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @57
COPY ~Eldritch_Magic/ITM/emsarev.itm~ ~override~ // Sword of Chaos +5 (Ascension)
  SAY NAME1 ~~
  SAY NAME2 @56
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @57
COPY ~Eldritch_Magic/ITM/BGEE/misc72.itm~ ~override~
  SAY 0x226 @224
COPY ~Eldritch_Magic/ITM/BGEE/misc73.itm~ ~override~
  SAY 0xae @224
COPY ~Eldritch_Magic/ITM/emheart.itm~ ~override~ // Black Heart of Kazgaroth
  SAY NAME1 ~~
  SAY NAME2 @220
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @221
COPY ~Eldritch_Magic/ITM/emhugh.itm~ ~override~ // Sword of Cymrych Hugh
  SAY NAME1 @42
  SAY NAME2 @255
  SAY UNIDENTIFIED_DESC @44
  SAY DESC @256
  SAY 0x19e @224
  SAY 0x1ce @224
  SAY 0x1fe @224
COPY ~Eldritch_Magic/ITM/emhide.itm~ ~override~ // Kazgaroth's Hide
  SAY NAME1 @225
  SAY NAME2 @222
  SAY UNIDENTIFIED_DESC @226
  SAY DESC @223
  SAY 0x22e @224
COPY ~Eldritch_Magic/ITM/EMAURIL.itm~ ~override~ // Breath of Auril +3
  SAY NAME1 ~~
  SAY NAME2 @257
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @258
COPY ~Eldritch_Magic/BAM/IAURIL.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMBBLA.itm~ ~override~ // Lore of the Bladesingers
  SAY NAME1 ~~
  SAY NAME2 @259
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @260
COPY ~Eldritch_Magic/ITM/EMBLOOD.itm~ ~override~ // Bathed-In-Blood +4
  SAY NAME1 ~~
  SAY NAME2 @261
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @262
COPY ~Eldritch_Magic/BAM/IBLOOD.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMCLOASC.itm~ ~override~ // Cloak of Scintillating Colors
  SAY NAME1 ~~
  SAY NAME2 @263
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @264
COPY ~Eldritch_Magic/BAM/ICLOAKSC.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMELFCHA.itm~ ~override~ // Elven Chain Mail of the Hand +3
  SAY NAME1 ~~
  SAY NAME2 @265
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @266
COPY ~Eldritch_Magic/BAM/IELFCHAN.bam~ ~override~
COPY ~Eldritch_Magic/BAM/GCHAN12.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMGLORY.itm~ ~override~ // The Glory of Suffering +6
  SAY NAME1 ~~
  SAY NAME2 @267
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @268
COPY ~Eldritch_Magic/BAM/IGLORY.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMJHOSWD.itm~ ~override~ // Singing Blade of Aihonen +5
  SAY NAME1 ~~
  SAY NAME2 @269
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @270
COPY ~Eldritch_Magic/BAM/IJHOSWD3.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMZZ36DG.itm~ ~override~ // Dead God's Dreaming +4, +6 vs. good
  SAY NAME1 ~~
  SAY NAME2 @271
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @272
COPY ~Eldritch_Magic/BAM/IZZ36DGD.bam~ ~override~
COPY ~Eldritch_Magic/Effects/ZZ36DGDH.eff~ ~override~
COPY ~Eldritch_Magic/Effects/ZZ36DGDD.eff~ ~override~
COPY ~Eldritch_Magic/Spells/EM428.spl~ ~override~
  SAY 0x8 @273
  SAY 0x50 @274
  SAY 0x18e @277
COPY ~Eldritch_Magic/Spells/EM714.spl~ ~override~
  SAY 0x8 @275
  SAY 0x50 @276
  SAY 0x21e @278
COPY ~Eldritch_Magic/BAM/conjuh.bam~ ~override~
COPY ~Eldritch_Magic/BAM/enchah.bam~ ~override~
COPY ~Eldritch_Magic/VVC/conjuh.vvc~ ~override~
COPY ~Eldritch_Magic/VVC/enchah.vvc~ ~override~
COPY ~Eldritch_Magic/BAM/EM428B.bam~ ~override~
COPY ~Eldritch_Magic/BAM/EM428C.bam~ ~override~
COPY ~Eldritch_Magic/BAM/EM714B.bam~ ~override~
COPY ~Eldritch_Magic/BAM/EM714C.bam~ ~override~
// Taerom Fuiruim (Thunderhammer Smithy - Beregost)
COPY_EXISTING ~TAERUM.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h06~ AFTER ~sw1h05~ #0 #0 #0 ~IDENTIFIED~ #1 // Flaming Burst Long Sword +1
// Sorcerous Sundries (Baldur's Gate)
COPY_EXISTING ~STO0703.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h07~ AFTER ~sw1h05~ #0 #0 #0 ~IDENTIFIED~ #1 // Frost-Fire Long Sword +2
 ADD_STORE_ITEM ~emsw1h02~ AFTER ~emsw1h07~ #0 #0 #0 ~IDENTIFIED~ #1 // Adamantite Long Sword of Biting +1
 ADD_STORE_ITEM ~CLCK15~ AFTER ~emsw1h02~ #0 #0 #0 ~IDENTIFIED~ #1 // Robe of the Good Archmagi
 ADD_STORE_ITEM ~CLCK16~ AFTER ~CLCK15~ #0 #0 #0 ~IDENTIFIED~ #1 // Robe of the Neutral Archmagi
// The Friendly Arm Inn
COPY_EXISTING ~FRIEND.sto~ ~override~
 ADD_STORE_ITEM ~embhaal~ AFTER ~shld06~ #1 #0 #0 ~IDENTIFIED~ #1 // Bhaal's Holy Symbol
// The High Hedge
COPY_EXISTING ~HIGHHEDG.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h05~ AFTER ~CLCK16~ #0 #0 #0 ~IDENTIFIED~ #1 // Silver Long Sword +2
// Ulgoth's Beard Store and Inn
COPY_EXISTING ~ULGOTH.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h10~ AFTER ~staf08~ #0 #0 #0 ~IDENTIFIED~ #1 // Mithral Long Sword +3
// Nashkel Store
COPY_EXISTING ~STO4803.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h03~ AFTER ~sw1h04~ #0 #0 #0 ~IDENTIFIED~ #1 // Masterwork Cold Iron Long Sword
// Black Lily
COPY_EXISTING ~STOBLACK.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h12~ AFTER ~sw1h07~ #0 #0 #0 ~IDENTIFIED~ #1 // Vampiric Short Sword +1
// Archmage spells: "mainly for... experiments." - Irenicus
///////////////////////////////////////////////////////////
// Fireball-Lightning Bolt
COPY ~Eldritch_Magic/Spells/EMIMPFB.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPLB.spl~ ~override~
COPY ~Eldritch_Magic/ITM/EMFBLB.itm~ ~override~
  SAY NAME1 @1001
  SAY NAME2 @1001
  SAY UNIDENTIFIED_DESC @1002
  SAY DESC @1002
COPY ~Eldritch_Magic/Spells/EMFBLB.spl~ ~override~
  SAY NAME1 @1001
  SAY NAME2 @1001
  SAY UNIDENTIFIED_DESC @1002
  SAY DESC @1002
// Wand of Fire and Lightning
COPY ~Eldritch_Magic/ITM/EMWAND05.itm~ ~override~
  SAY NAME1 @5000
  SAY NAME2 @5001
  SAY UNIDENTIFIED_DESC @5002
  SAY DESC @5003
// Improved Magic Missile
COPY ~Eldritch_Magic/Spells/EMMM0.spl~ ~override~
COPY ~Eldritch_Magic/ITM/EMIMPMM.itm~ ~override~
  SAY NAME1 @1003
  SAY NAME2 @1003
  SAY UNIDENTIFIED_DESC @1004
  SAY DESC @1004
COPY ~Eldritch_Magic/Spells/EMIMPMM.spl~ ~override~
  SAY NAME1 @1003
  SAY NAME2 @1003
  SAY UNIDENTIFIED_DESC @1004
  SAY DESC @1004
// Shadovar Wraithform
COPY ~Eldritch_Magic/ITM/EMWRAITH.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMIMPWF.itm~ ~override~
  SAY NAME1 @1005
  SAY NAME2 @1005
  SAY UNIDENTIFIED_DESC @1006
  SAY DESC @1006
COPY ~Eldritch_Magic/Spells/EMIMPWF.spl~ ~override~
  SAY NAME1 @1005
  SAY NAME2 @1005
  SAY UNIDENTIFIED_DESC @1006
  SAY DESC @1006
// Greater Animate Dead
COPY ~Eldritch_Magic/Creatures/EMSKELWA.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/EMSKELWB.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/EMSKELWC.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/EMSKELWD.cre~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL19.eff~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL23.eff~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL27.eff~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL31.eff~ ~override~
COPY ~Eldritch_Magic/ITM/EMSKELWB.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMSKELWC.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMSKELWD.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMIMPAD.itm~ ~override~
  SAY NAME1 @1007
  SAY NAME2 @1007
  SAY UNIDENTIFIED_DESC @1008
  SAY DESC @1008
COPY ~Eldritch_Magic/Spells/EMIMPAD.spl~ ~override~
  SAY NAME1 @1007
  SAY NAME2 @1007
  SAY UNIDENTIFIED_DESC @1008
  SAY DESC @1008
// Shapeshift: Lycanthrope
COPY ~Eldritch_Magic/Spells/EMWW.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMGWW.spl~ ~override~
COPY ~Eldritch_Magic/ITM/EMSSWW.itm~ ~override~
  SAY NAME1 @1009
  SAY NAME2 @1009
  SAY UNIDENTIFIED_DESC @1010
  SAY DESC @1010
COPY ~Eldritch_Magic/Spells/EMSSWW.spl~ ~override~
  SAY NAME1 @1009
  SAY NAME2 @1009
  SAY UNIDENTIFIED_DESC @1010
  SAY DESC @1010
// Shapeshift: Demon Lord
COPY ~Eldritch_Magic/Spells/EMDL.spl~ ~override~
COPY ~Eldritch_Magic/Creatures/EMTANAR.cre~ ~override~
COPY ~Eldritch_Magic/ITM/EMTANAR.itm~ ~override~
COPY ~Eldritch_Magic/Spells/EMSSDL.spl~ ~override~
  SAY NAME1 @1011
  SAY NAME2 @1011
  SAY UNIDENTIFIED_DESC @1012
  SAY DESC @1012
// Call Lightning-Flame Strike
COPY ~Eldritch_Magic/Spells/EMIMPCL.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPFS.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCLFS.spl~ ~override~
  SAY NAME1 @1013
  SAY NAME2 @1013
  SAY UNIDENTIFIED_DESC @1014
  SAY DESC @1014
// Contingency I
COPY ~Eldritch_Magic/Spells/EMARMOR.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMPROEVI.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMPROPET.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCONT1.spl~ ~override~
  SAY NAME1 @1015
  SAY NAME2 @1015
  SAY UNIDENTIFIED_DESC @1016
  SAY DESC @1016
// Contingency II
COPY ~Eldritch_Magic/Spells/EMIMPVOC.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPBLU.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPRF.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCONT2.spl~ ~override~
  SAY NAME1 @1017
  SAY NAME2 @1017
  SAY UNIDENTIFIED_DESC @1018
  SAY DESC @1018
// Contingency III
COPY ~Eldritch_Magic/Spells/EMIMPStS.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPSB.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPSR.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCONT3.spl~ ~override~
  SAY NAME1 @1019
  SAY NAME2 @1019
  SAY UNIDENTIFIED_DESC @1020
  SAY DESC @1020
// Improved Chromatic Orb
COPY ~Eldritch_Magic/Spells/EMIMPCO.spl~ ~override~
  SAY NAME1 @1021
  SAY NAME2 @1021
  SAY UNIDENTIFIED_DESC @1022
  SAY DESC @1022
// Unweave Magic
COPY ~Eldritch_Magic/Spells/EMIMPPS.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPKW.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPSS.spl~ ~override~
  SAY NAME1 @1023
  SAY NAME2 @1023
  SAY UNIDENTIFIED_DESC @1024
  SAY DESC @1024
// Call Upon Abyss: Baphomet
COPY ~Eldritch_Magic/Spells/EMIMPSC.spl~ ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1026
  SAY DESC @1026
// Adds HLAs (BGEE) Not yet SoD compatible!
// Bard HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUBA0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUBA1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUBA2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUBA3.2DA~ ~override~
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL910.spl~ ~override~ // Set Spike Trap
  SAY 0x8  @1043
  SAY 0x50 @1044
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL911.spl~ ~override~ // Set Exploding Trap
  SAY 0x8  @1045
  SAY 0x50 @1046
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL912.spl~ ~override~ // Set Time Trap
  SAY 0x8  @1047
  SAY 0x50 @1048
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL913.spl~ ~override~ // Evasion
  SAY 0x8  @1049
  SAY 0x50 @1050
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL914.spl~ ~override~ // Greater Evasion
  SAY 0x8  @1051
  SAY 0x50 @1052
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL915.spl~ ~override~ // Use Any Item
  SAY 0x8  @1053
  SAY 0x50 @1054
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL916.spl~ ~override~ // Assassination
  SAY 0x8  @1055
  SAY 0x50 @1056
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL917.spl~ ~override~ // Avoid Death
  SAY 0x8  @1057
  SAY 0x50 @1058
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL918.spl~ ~override~ // Alchemy
  SAY 0x8  @1059
  SAY 0x50 @1060
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL919.spl~ ~override~ // Scribe Scrolls
  SAY 0x8  @1061
  SAY 0x50 @1062
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL920.spl~ ~override~ // Enhanced Bard Song
  SAY 0x8  @1063
  SAY 0x50 @1064
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL921.spl~ ~override~ // Magic Flute
  SAY 0x8  @1065
  SAY 0x50 @1066
// Barbarian HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUBB0.2DA~ ~override~
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL900.spl~ ~override~ // Whirlwind Attack
  SAY 0x8  @1067
  SAY 0x50 @1068
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL901.spl~ ~override~ // Greater Whirlwind Attack
  SAY 0x8  @1069
  SAY 0x50 @1070
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL902.spl~ ~override~ // Deathblow
  SAY 0x8  @1071
  SAY 0x50 @1072
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL903.spl~ ~override~ // Greater Deathblow
  SAY 0x8  @1073
  SAY 0x50 @1074
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL904.spl~ ~override~ // Resist Magic
  SAY 0x8  @1075
  SAY 0x50 @1076
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL905.spl~ ~override~ // Critical Strike
  SAY 0x8  @1077
  SAY 0x50 @1078
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL906.spl~ ~override~ // Power Attack
  SAY 0x8  @1079
  SAY 0x50 @1080
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL907.spl~ ~override~ // Hardiness
  SAY 0x8  @1081
  SAY 0x50 @1082
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL908.spl~ ~override~ // War Cry
  SAY 0x8  @1083
  SAY 0x50 @1084
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL909.spl~ ~override~ // Smite
  SAY 0x8  @1085
  SAY 0x50 @1086
// Grizzly Bear HLAs (just in case)
COPY ~Eldritch_Magic/2DA/BG2EE/LUBEA.2DA~ ~override~
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL922.spl~ ~override~ // Tracking
  SAY 0x8  @1087
  SAY 0x50 @1088
// Cleric HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUCL0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUCL1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUCL2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUCL3.2DA~ ~override~
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR721.spl~ ~override~ // Energy Blades
  SAY 0x8  @1089
  SAY 0x50 @1090
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR722.spl~ ~override~ // Storm of Vengeance
  SAY 0x8  @1091
  SAY 0x50 @1092
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR723.spl~ ~override~ // Elemental Summoning
  SAY 0x8  @1093
  SAY 0x50 @1094
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR724.spl~ ~override~ // Greater Elemental Summoning
  SAY 0x8  @1095
  SAY 0x50 @1096
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR725.spl~ ~override~ // Globe of Blades
  SAY 0x8  @1097
  SAY 0x50 @1098
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR726.spl~ ~override~ // Summon Deva
  SAY 0x8  @1099
  SAY 0x50 @1100
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR727.spl~ ~override~ // Summon Fallen Deva
  SAY 0x8  @1101
  SAY 0x50 @1102
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR728.spl~ ~override~ // Implosion
  SAY 0x8  @1103
  SAY 0x50 @1104
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR729.spl~ ~override~ // Mass Raise Dead
  SAY 0x8  @1105
  SAY 0x50 @1106
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR730.spl~ ~override~ // Aura of Flaming Death
  SAY 0x8  @1107
  SAY 0x50 @1108
// Cleric/Mage HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUCM0.2DA~ ~override~
// Cleric/Ranger HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUCR0.2DA~ ~override~
// Cleric/Thief HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUCT0.2DA~ ~override~
// Druid HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUDR0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUDR1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUDR2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUDR3.2DA~ ~override~
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR731.spl~ ~override~ // Fire Elemental Transformation
  SAY 0x8  @1109
  SAY 0x50 @1110
COPY ~Eldritch_Magic/Spells/BG2EE/SPPR732.spl~ ~override~ // Earth Elemental Transformation
  SAY 0x8  @1111
  SAY 0x50 @1112
// Fighter/Cleric HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFC0.2DA~ ~override~
// Fighter/Druid HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFD0.2DA~ ~override~
// Fighter HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFI0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUFI1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUFI2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUFI3.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUFI4.2DA~ ~override~
// Fighter/Mage HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFM0.2DA~ ~override~
// Fighter/Mage/Cleric HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFMC.2DA~ ~override~
// Fighter/Mage/Thief HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFMT.2DA~ ~override~
// Fighter/Thief HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUFT0.2DA~ ~override~
// Mage HLAs
ACTION_IF (FILE_EXISTS_IN_GAME ~EMIMPFB.spl~) BEGIN
  COPY ~Eldritch_Magic/2DA/BG2EE/LUMA0.2da~ ~override~        // Includes level 10 Archmage spells added in BGEE: Item Expansion
END
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~EMIMPFB.spl~) BEGIN
  COPY ~Eldritch_Magic/2DA/BG2EE/HLAs/LUMA0.2da~ ~override~   // Does not include level 10 Archmage spells added in BGEE: Item Expansion
END
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA3.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA4.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA5.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA6.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA7.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMA8.2DA~ ~override~
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL928.spl~ ~override~ // Extra Level 6 Spell
  SAY 0x8  @1027
  SAY 0x50 @1028
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL929.spl~ ~override~ // Extra Level 7 Spell
  SAY 0x8  @1029
  SAY 0x50 @1030
COPY ~Eldritch_Magic/Spells/BG2EE/SPCL930.spl~ ~override~ // Extra Level 8 Spell
  SAY 0x8  @1031
  SAY 0x50 @1032
COPY ~Eldritch_Magic/Spells/BG2EE/SPWI921.spl~ ~override~ // Improved Alacrity
  SAY 0x8  @1033
  SAY 0x50 @1034
COPY ~Eldritch_Magic/Spells/BG2EE/SPWI922.spl~ ~override~ // Dragon's Breath
  SAY 0x8  @1035
  SAY 0x50 @1036
COPY ~Eldritch_Magic/Spells/BG2EE/SPWI923.spl~ ~override~ // Summon Planetar
  SAY 0x8  @1037
  SAY 0x50 @1038
COPY ~Eldritch_Magic/Spells/BG2EE/SPWI924.spl~ ~override~ // Summon Dark Planetar
  SAY 0x8  @1039
  SAY 0x50 @1040
COPY ~Eldritch_Magic/Spells/BG2EE/SPWI925.spl~ ~override~ // Comet
  SAY 0x8  @1041
  SAY 0x50 @1042
// Monk HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUMO0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMO1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUMO2.2DA~ ~override~
// Mage/Thief HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUMT0.2DA~ ~override~
// Paladin HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUPA0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUPA1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUPA2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUPA3.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUPA4.2DA~ ~override~
// Priest HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUPR0.2DA~ ~override~
// Ranger HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUSO0.2DA~ ~override~
// Sorcerer HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LURA0.2DA~ ~override~
// Thief HLAs
COPY ~Eldritch_Magic/2DA/BG2EE/LUTH0.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUTH1.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUTH2.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUTH3.2DA~ ~override~
COPY ~Eldritch_Magic/2DA/BG2EE/LUTH4.2DA~ ~override~
COPY ~Eldritch_Magic/BAM/BG2EE/SPCL900B.bam~ ~override~
// Many more BAMs to add
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL902.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL902A.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL903.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL903A.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL906.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL906A.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL906B.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL909A.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL909B.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL909C.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL934E.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL934G.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPCL934N.eff~ ~override~
COPY ~Eldritch_Magic/Effects/BG2EE/SPPR707.eff~ ~override~
 PRINT ~“He who fights with monsters should look to it that he himself does not become a monster . . . when you gaze long into the abyss the abyss also gazes into you”
- Friedrich Nietzsche~
END

// BG2EE

ACTION_IF GAME_IS ~bg2ee~ BEGIN
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~finsarev.itm~) BEGIN
  COMPILE ~Eldritch_Magic/BAF/Ascension~
  COMPILE ~Eldritch_Magic/Dialog/Ascension~
  COPY ~Eldritch_Magic/BAF/Ascension/sarev25.bcs~ ~override~
END
COPY ~Eldritch_Magic/ITM/Ascension/finsarev.itm~ ~override~
  SAY NAME2 @3000
  SAY DESC  @3001
COPY ~Eldritch_Magic/Effects/Ascension/reaver.eff~ ~override~
COPY ~Eldritch_Magic/Spells/Ascension/reaver.spl~ ~override~
COPY ~Eldritch_Magic/Spells/Ascension/reavimm.spl~ ~override~

COPY ~Eldritch_Magic/Creatures/hlrevan.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/idemon01.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/idemon02.cre~ ~override~
//COPY_EXISTING ~idemon01.cre~ ~override/alynar.cre~
//  ADD_CRE_ITEM ~itemname~ #charge1 #charge2 #charge3 ~Flags~ ~Inventory Slots~ [EQUIP] [TWOHANDED]
//COPY_EXISTING ~idemon02.cre~ ~override/alynar.cre~
//  ADD_CRE_ITEM ~itemname~ #charge1 #charge2 #charge3 ~Flags~ ~Inventory Slots~ [EQUIP] [TWOHANDED]
//COPY_EXISTING ~hlrevan.cre~ ~override/alynar.cre~
//  ADD_CRE_ITEM ~itemname~ #charge1 #charge2 #charge3 ~Flags~ ~Inventory Slots~ [EQUIP] [TWOHANDED]

COPY ~Eldritch_Magic/Creatures/Sar1L.BMP~ ~override/Sar1L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar2L.BMP~ ~override/Sar2L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar1L.BMP~ ~portraits~
COPY ~Eldritch_Magic/Creatures/Sar2L.BMP~ ~portraits~
COPY ~Eldritch_Magic/Creatures/Sar1M.BMP~ ~override/Sar1L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar2M.BMP~ ~override/Sar2L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar1M.BMP~ ~portraits~
COPY ~Eldritch_Magic/Creatures/Sar2M.BMP~ ~portraits~
COPY  ~Eldritch_Magic/Spells/emcdcha.spl~   ~override~
      SAY 0xfe @219 //You feel a tug from the Pocket Plane as an artifact lost to time materializes among your possessions. Surely such a happening is linked to your powerful heritage.
COPY  ~Eldritch_Magic/Spells/emcdbls.spl~   ~override~
      SAY 0x15e @213 //You have been acknowledged by the Bladesinger's Guild.
COPY  ~Eldritch_Magic/Spells/emcdsw1.spl~   ~override~
      SAY 0xfe @214 //You are an exemplary Bladesinger and a hero among elves. The Gods themselves have taken notice of your righteous fury and now the Seldarine have blessed you with the tool to exact it. Be advised not to abuse a divine gift.
COPY  ~Eldritch_Magic/Effects/emundead.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emdemon.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh1.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh2.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh3.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/em2d6.eff~   ~override~
COPY  ~Eldritch_Magic/Dialog/emsw1h01.dlg~   ~override~
      SAY 0x34  @200 //(The sword flashes for a moment, then permeates your mind with melodic Elven whispers.)
      SAY 0x44  @201 // ...
      SAY 0x54  @202 // "I am as I have always been."
      SAY 0x64  @204 //(The sword emits a shockingly demi-human sigh) "42."
      SAY 0x74  @206 //(The sword is silent a moment.) "That would have to be a hectaoncheire, 'hundredhanded one' - a few Gods fell that day. Pray you never face one, much less two."
      SAY 0x84  @208 // "I may be a holy artifact forged by the Gods, but I'm still a sword. Aren't there any evil Bhaalspawn left?"
      SAY 0x98  @198 // Never mind. Let's just continue on for now.
      SAY 0xb8  @199 // What's your status, sword?
      SAY 0xd8  @203 // What is the answer to life, the universe, and everything?
      SAY 0xf8  @205 // What's the most powerful foe you've vanquished?
      SAY 0x118 @207 // What would you have me do, O Sentient Sword?
COMPILE ~Eldritch_Magic/Dialog~
COPY  ~Eldritch_Magic/Spells/emsare1.spl~   ~override~
      SAY 0xce @94 //Blades
COPY  ~Eldritch_Magic/Spells/emsare2.spl~   ~override~
      SAY 0xce @95 //Spikes
COPY_EXISTING ~lunumab.2da~ ~override~
  APPEND ITEMDIAL.2da ~EMSW1H01      5689   EMSW1H01~
COPY_EXISTING ~item_use.2da~ ~override~
  APPEND item_use.2da ~emplat01   SAREVOK    9382       2~
  APPEND item_use.2da ~emsw2h01   SAREVOK    9382       2~
  APPEND item_use.2da ~emsarev   SAREVOK    9382       2~
COPY ~Eldritch_Magic/ITM/emboot01.itm~ ~override~ // Elven Boots of Speed: The Paws of the Lythari
  SAY NAME1 @26
  SAY NAME2 @27
  SAY UNIDENTIFIED_DESC @28
  SAY DESC @29
  SAY 0x15e @96 // Bladesinger
COPY ~Eldritch_Magic/ITM/emchan01.itm~ ~override~ // Holy Elven Chain +6
  SAY NAME1 @30
  SAY NAME2 @31
  SAY UNIDENTIFIED_DESC @32
  SAY DESC @33
  SAY 0x3fe @96
COPY ~Eldritch_Magic/ITM/emclck01.itm~ ~override~ // Bladesinger's Shroud
  SAY NAME1 @34
  SAY NAME2 @35
  SAY UNIDENTIFIED_DESC @36
  SAY DESC @37
  SAY 0x2b6 @96
COPY ~Eldritch_Magic/ITM/emring01.itm~ ~override~ // Bladesinger's Signet
  SAY NAME1 @38
  SAY NAME2 @39
  SAY UNIDENTIFIED_DESC @40
  SAY DESC @41
  SAY 0x2de @96
COPY ~Eldritch_Magic/BAM/emsw1h01.bam~ ~override~
COPY ~Eldritch_Magic/ITM/emsw1h01.itm~ ~override~// Seldarine's Fury +6: Shame of the Gods
  SAY NAME1 @42
  SAY NAME2 @43
  SAY UNIDENTIFIED_DESC @44
  SAY DESC @45
  SAY 0x586 @96
COPY ~Eldritch_Magic/ITM/emsw1h11.itm~ ~override~ // Angharradh's Song
  SAY NAME1 ~~
  SAY NAME2 @47
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @49
  SAY 0x1f6 @96
COPY ~Eldritch_Magic/ITM/embelt25.itm~ ~override~ // Girdle of Titan Strength
  SAY NAME1 ~~
  SAY NAME2 @58
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @59
COPY ~Eldritch_Magic/ITM/emthay.itm~ ~override~ // Red Robe of Thay
  SAY NAME1 ~~
  SAY NAME2 @60
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @61
  SAY 0x36e @97 // Red Wizard of Thay
COPY ~Eldritch_Magic/ITM/emsw1h04.itm~ ~override~ // Blue Flame Taragarth +3
  SAY NAME1 ~~
  SAY NAME2 @62
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @63
COPY ~Eldritch_Magic/ITM/emdagg01.itm~ ~override~ // Netherese Spellblade
  SAY NAME1 ~~
  SAY NAME2 @64
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @65
COPY ~Eldritch_Magic/ITM/emsw1h08.itm~ ~override~ // Plasma Blade of Kossuth: Igneus Nova
  SAY NAME1 ~~
  SAY NAME2 @66
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @67
COPY ~Eldritch_Magic/BAM/phelm29.bmp~ ~override~
COPY ~Eldritch_Magic/ITM/empsion.itm~ ~override~ // Drow Psionicist's Cowl
  SAY NAME1 ~~
  SAY NAME2 @68
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @69
COPY ~Eldritch_Magic/ITM/emveye.itm~ ~override~ // Eye of Vecna
  SAY NAME1 ~~
  SAY NAME2 @70
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @71
COPY ~Eldritch_Magic/ITM/emvhand.itm~ ~override~ // Hand of Vecna
  SAY NAME1 ~~
  SAY NAME2 @72
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @73
// COPY ~Eldritch_Magic/ITM/emcesp01.itm~ ~override~ // Claw of Kazgaroth
//  SAY NAME1 ~~
//  SAY NAME2 @50
//  SAY UNIDENTIFIED_DESC ~~
//  SAY DESC @51
COPY ~Eldritch_Magic/ITM/emimoen.itm~ ~override~ // Imoen's Belt
  SAY NAME1 ~~
  SAY NAME2 @52
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @53
  SAY 0x2de @98 // IMOEN
COPY_EXISTING ~cuimoen.cre~ ~override/cuimoen.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~cuimoen2.cre~ ~override/cuimoen2.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~cuimoen3.cre~ ~override/cuimoen3.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~dpimo01.cre~ ~override/dpimo01.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~dream1.cre~ ~override/dream1.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~drim01.cre~ ~override/drim01.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~drim02.cre~ ~override/drim02.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~imoen.cre~ ~override/imoen.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~imoen15.cre~ ~override/imoen15.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~imoen211.cre~ ~override/imoen211.cre~ // ***
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~imoen213.cre~ ~override/imoen213.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~imoendrm.cre~ ~override/imoendrm.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY_EXISTING ~ohb1imoe.cre~ ~override/ohb1imoe.cre~
  ADD_CRE_ITEM ~EMIMOEN~ #0 #0 #0 ~IDENTIFIED~ ~BELT~
COPY ~Eldritch_Magic/ITM/emplat01.itm~ ~override~ // Sarevok's Bladed Armor +5
  SAY NAME1 ~~
  SAY NAME2 @54
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @55
COPY ~Eldritch_Magic/ITM/emsw2h01.itm~ ~override~ // Sword of Chaos +5
  SAY NAME1 ~~
  SAY NAME2 @56
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @57
COPY ~Eldritch_Magic/ITM/emsarev.itm~ ~override~ // Sword of Chaos +5 (Ascension)
  SAY NAME1 ~~
  SAY NAME2 @56
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @57
COPY ~Eldritch_Magic/ITM/emheart.itm~ ~override~ // Black Heart of Kazgaroth
  SAY NAME1 ~~
  SAY NAME2 @220
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @221
COPY ~Eldritch_Magic/ITM/emhugh.itm~ ~override~ // Sword of Cymrych Hugh
  SAY NAME1 @42
  SAY NAME2 @255
  SAY UNIDENTIFIED_DESC @44
  SAY DESC @256
  SAY 0x19e @224
  SAY 0x1ce @224
  SAY 0x1fe @224
COPY ~Eldritch_Magic/ITM/emhide.itm~ ~override~ // Kazgaroth's Hide
  SAY NAME1 @225
  SAY NAME2 @222
  SAY UNIDENTIFIED_DESC @226
  SAY DESC @223
  SAY 0x22e @224
COPY ~Eldritch_Magic/ITM/EMAURIL.itm~ ~override~ // Breath of Auril +3
  SAY NAME1 ~~
  SAY NAME2 @257
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @258
COPY ~Eldritch_Magic/BAM/IAURIL.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMBBLA.itm~ ~override~ // Lore of the Bladesingers
  SAY NAME1 ~~
  SAY NAME2 @259
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @260
COPY ~Eldritch_Magic/ITM/EMBLOOD.itm~ ~override~ // Bathed-In-Blood +4
  SAY NAME1 ~~
  SAY NAME2 @261
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @262
COPY ~Eldritch_Magic/BAM/IBLOOD.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMCLOASC.itm~ ~override~ // Cloak of Scintillating Colors
  SAY NAME1 ~~
  SAY NAME2 @263
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @264
COPY ~Eldritch_Magic/BAM/ICLOAKSC.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMELFCHA.itm~ ~override~ // Elven Chain Mail of the Hand +3
  SAY NAME1 ~~
  SAY NAME2 @265
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @266
COPY ~Eldritch_Magic/BAM/IELFCHAN.bam~ ~override~
COPY ~Eldritch_Magic/BAM/GCHAN12.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMGLORY.itm~ ~override~ // The Glory of Suffering +6
  SAY NAME1 ~~
  SAY NAME2 @267
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @268
COPY ~Eldritch_Magic/BAM/IGLORY.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMJHOSWD.itm~ ~override~ // Singing Blade of Aihonen +5
  SAY NAME1 ~~
  SAY NAME2 @269
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @270
COPY ~Eldritch_Magic/BAM/IJHOSWD3.bam~ ~override~
COPY ~Eldritch_Magic/ITM/EMZZ36DG.itm~ ~override~ // Dead God's Dreaming +4, +6 vs. good
  SAY NAME1 ~~
  SAY NAME2 @271
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @272
COPY ~Eldritch_Magic/BAM/IZZ36DGD.bam~ ~override~
COPY ~Eldritch_Magic/Effects/ZZ36DGDH.eff~ ~override~
COPY ~Eldritch_Magic/Effects/ZZ36DGDD.eff~ ~override~
COPY ~Eldritch_Magic/Spells/EM428.spl~ ~override~
  SAY 0x8 @273
  SAY 0x50 @274
  SAY 0x18e @277
COPY ~Eldritch_Magic/Spells/EM714.spl~ ~override~
  SAY 0x8 @275
  SAY 0x50 @276
  SAY 0x21e @278
COPY ~Eldritch_Magic/BAM/conjuh.bam~ ~override~
COPY ~Eldritch_Magic/BAM/enchah.bam~ ~override~
COPY ~Eldritch_Magic/VVC/conjuh.vvc~ ~override~
COPY ~Eldritch_Magic/VVC/enchah.vvc~ ~override~
COPY ~Eldritch_Magic/BAM/EM428B.bam~ ~override~
COPY ~Eldritch_Magic/BAM/EM428C.bam~ ~override~
COPY ~Eldritch_Magic/BAM/EM714B.bam~ ~override~
COPY ~Eldritch_Magic/BAM/EM714C.bam~ ~override~
COPY_EXISTING ~RIBALD3.sto~ ~override~
 ADD_STORE_ITEM ~emdagg01~ AFTER ~DAGG15~ #3 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~EMPSION~ AFTER ~AX1H11~ #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~emthay~ AFTER ~POTN42~ #0 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~WMART1.sto~ ~override~
 ADD_STORE_ITEM ~emsw1h08~ AFTER ~WAAXE~ #1 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~embelt25~ LAST #0 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~WMART2.sto~ ~override~
 ADD_STORE_ITEM ~emvhand~ AFTER ~WA2ROBE~ #3 #1 #1 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~emveye~ BEFORE ~WA2S1H~ #3 #1 #1 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~emsw1h11~ AFTER ~WA2SHIEL~ #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~emsw1h04~ LAST #0 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~25SPELL2.sto~ ~override~
 ADD_STORE_ITEM ~emplat01~ AFTER ~RING02~ #0 #0 #0 ~IDENTIFIED~ #1
// ADD_STORE_ITEM ~emcesp01~ LAST #0 #0 #0 ~IDENTIFIED~ #1
COPY ~Eldritch_Magic/ITM/BGEE/misc72.itm~ ~override~ // The Claw of Kazgaroth
  SAY 0x226 @224 // It seems that even death and dismemberment has not eased Kazgaroth's hatred for the Sword of Cymrych Hugh.
COPY ~Eldritch_Magic/ITM/BGEE/misc73.itm~ ~override~ // The Horn of Kazgaroth
  SAY 0xae @224 // It seems that even death and dismemberment has not eased Kazgaroth's hatred for the Sword of Cymrych Hugh.
COPY_EXISTING ~BAG20.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG21.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG22.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG23.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG24.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG25.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG26.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG27.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG28.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG29.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
COPY_EXISTING ~BAG30.sto~ ~override~
 ADD_STORE_ITEM ~SW2H16~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC72~ LAST #0 #0 #0 ~IDENTIFIED~ #1
 ADD_STORE_ITEM ~MISC73~ LAST #30 #0 #0 ~IDENTIFIED~ #1
// BGEE- Won't appear in BG2EE
COPY  ~Eldritch_Magic/Effects/emlaw.eff~   ~override~
COPY ~Eldritch_Magic/ITM/emsw1h05.itm~ ~override~ // Silver Long Sword +2
  SAY NAME1 ~~
  SAY NAME2 @102
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @103
COPY ~Eldritch_Magic/ITM/emsw1h06.itm~ ~override~ // Flaming Burst Long Sword +1
  SAY NAME1 ~~
  SAY NAME2 @104
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @105
COPY ~Eldritch_Magic/ITM/emsw1h07.itm~ ~override~ // Frost-Fire Long Sword +2
  SAY NAME1 ~~
  SAY NAME2 @106
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @107
COPY ~Eldritch_Magic/ITM/emsw1h10.itm~ ~override~ // Mithral Long Sword +3
  SAY NAME1 ~~
  SAY NAME2 @108
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @109
COPY ~Eldritch_Magic/ITM/emsw1h02.itm~ ~override~ // Adamantine Long Sword of Biting +1
  SAY NAME1 ~~
  SAY NAME2 @110
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @111
COPY ~Eldritch_Magic/ITM/emsw1h12.itm~ ~override~ // Vampiric Short Sword +1
  SAY NAME1 ~~
  SAY NAME2 @112
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @113
COPY ~Eldritch_Magic/ITM/emsw1h03.itm~ ~override~ // Masterwork Cold Iron Long Sword
  SAY NAME1 ~~
  SAY NAME2 @114
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @115
COPY ~Eldritch_Magic/ITM/emsw1h13.itm~ ~override~ // Elemental Long Sword +1
  SAY NAME1 ~~
  SAY NAME2 @116
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @117
COPY ~Eldritch_Magic/ITM/emsw1h09.itm~ ~override~ // Holy Avenger Long Sword +3
  SAY NAME1 ~~
  SAY NAME2 @118
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @119
COPY ~Eldritch_Magic/ITM/embhaal.itm~ ~override~ // Bhaal's Holy Symbol
  SAY NAME1 ~~
  SAY NAME2 @120
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @121
COPY ~Eldritch_Magic/ITM/emchanco.itm~ ~override~ // Elven Chain Mail of the Collector
  SAY NAME1 ~~
  SAY NAME2 @140
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @141
// Fireball-Lightning Bolt
COPY ~Eldritch_Magic/Spells/EMIMPFB.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPLB.spl~ ~override~
COPY ~Eldritch_Magic/ITM/EMFBLB.itm~ ~override~
  SAY NAME1 @1001
  SAY NAME2 @1001
  SAY UNIDENTIFIED_DESC @1002
  SAY DESC @1002
COPY ~Eldritch_Magic/Spells/EMFBLB.spl~ ~override~
  SAY NAME1 @1001
  SAY NAME2 @1001
  SAY UNIDENTIFIED_DESC @1002
  SAY DESC @1002
// Wand of Fire and Lightning
COPY ~Eldritch_Magic/ITM/EMWAND05.itm~ ~override~
  SAY NAME1 @2001
  SAY NAME2 @2002
  SAY UNIDENTIFIED_DESC @2003
  SAY DESC @2004
// Improved Magic Missile
COPY ~Eldritch_Magic/Spells/EMMM0.spl~ ~override~
COPY ~Eldritch_Magic/ITM/EMIMPMM.itm~ ~override~
  SAY NAME1 @1003
  SAY NAME2 @1003
  SAY UNIDENTIFIED_DESC @1004
  SAY DESC @1004
COPY ~Eldritch_Magic/Spells/EMIMPMM.spl~ ~override~
  SAY NAME1 @1003
  SAY NAME2 @1003
  SAY UNIDENTIFIED_DESC @1004
  SAY DESC @1004
// Shadovar Wraithform
COPY ~Eldritch_Magic/ITM/EMWRAITH.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMIMPWF.itm~ ~override~
  SAY NAME1 @1005
  SAY NAME2 @1005
  SAY UNIDENTIFIED_DESC @1006
  SAY DESC @1006
COPY ~Eldritch_Magic/Spells/EMIMPWF.spl~ ~override~
  SAY NAME1 @1005
  SAY NAME2 @1005
  SAY UNIDENTIFIED_DESC @1006
  SAY DESC @1006
// Greater Animate Dead
COPY ~Eldritch_Magic/Creatures/EMSKELWA.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/EMSKELWB.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/EMSKELWC.cre~ ~override~
COPY ~Eldritch_Magic/Creatures/EMSKELWD.cre~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL19.eff~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL23.eff~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL27.eff~ ~override~
COPY ~Eldritch_Magic/Effects/SPANDL31.eff~ ~override~
COPY ~Eldritch_Magic/ITM/EMSKELWB.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMSKELWC.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMSKELWD.itm~ ~override~
COPY ~Eldritch_Magic/ITM/EMIMPAD.itm~ ~override~
  SAY NAME1 @1007
  SAY NAME2 @1007
  SAY UNIDENTIFIED_DESC @1008
  SAY DESC @1008
COPY ~Eldritch_Magic/Spells/EMIMPAD.spl~ ~override~
  SAY NAME1 @1007
  SAY NAME2 @1007
  SAY UNIDENTIFIED_DESC @1008
  SAY DESC @1008
// Shapeshift: Lycanthrope
COPY ~Eldritch_Magic/Spells/EMWW.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMGWW.spl~ ~override~
COPY ~Eldritch_Magic/ITM/EMSSWW.itm~ ~override~
  SAY NAME1 @1009
  SAY NAME2 @1009
  SAY UNIDENTIFIED_DESC @1010
  SAY DESC @1010
COPY ~Eldritch_Magic/Spells/EMSSWW.spl~ ~override~
  SAY NAME1 @1009
  SAY NAME2 @1009
  SAY UNIDENTIFIED_DESC @1010
  SAY DESC @1010
// Shapeshift: Demon Lord
COPY ~Eldritch_Magic/Spells/EMDL.spl~ ~override~
COPY ~Eldritch_Magic/Creatures/EMTANAR.cre~ ~override~
COPY ~Eldritch_Magic/ITM/EMTANAR.itm~ ~override~
COPY ~Eldritch_Magic/Spells/EMSSDL.spl~ ~override~
  SAY NAME1 @1011
  SAY NAME2 @1011
  SAY UNIDENTIFIED_DESC @1012
  SAY DESC @1012
// Call Lightning-Flame Strike
COPY ~Eldritch_Magic/Spells/EMIMPCL.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPFS.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCLFS.spl~ ~override~
  SAY NAME1 @1013
  SAY NAME2 @1013
  SAY UNIDENTIFIED_DESC @1014
  SAY DESC @1014
// Contingency I
COPY ~Eldritch_Magic/Spells/EMARMOR.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMPROEVI.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMPROPET.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCONT1.spl~ ~override~
  SAY NAME1 @1015
  SAY NAME2 @1015
  SAY UNIDENTIFIED_DESC @1016
  SAY DESC @1016
// Contingency II
COPY ~Eldritch_Magic/Spells/EMIMPVOC.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPBLU.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPRF.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCONT2.spl~ ~override~
  SAY NAME1 @1017
  SAY NAME2 @1017
  SAY UNIDENTIFIED_DESC @1018
  SAY DESC @1018
// Contingency III
COPY ~Eldritch_Magic/Spells/EMIMPStS.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPSB.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPSR.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMCONT3.spl~ ~override~
  SAY NAME1 @1019
  SAY NAME2 @1019
  SAY UNIDENTIFIED_DESC @1020
  SAY DESC @1020
// Improved Chromatic Orb
COPY ~Eldritch_Magic/Spells/EMIMPCO.spl~ ~override~
  SAY NAME1 @1021
  SAY NAME2 @1021
  SAY UNIDENTIFIED_DESC @1022
  SAY DESC @1022
// Unweave Magic
COPY ~Eldritch_Magic/Spells/EMIMPPS.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPKW.spl~ ~override~
COPY ~Eldritch_Magic/Spells/EMIMPSS.spl~ ~override~
  SAY NAME1 @1023
  SAY NAME2 @1023
  SAY UNIDENTIFIED_DESC @1024
  SAY DESC @1024
// Call Upon Abyss: Baphomet
COPY ~Eldritch_Magic/Spells/EMIMPSC.spl~ ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1026
  SAY DESC @1026
 PRINT ~“He who fights with monsters should look to it that he himself does not become a monster . . . when you gaze long into the abyss the abyss also gazes into you”
- Friedrich Nietzsche~
END

// IWDEE

ACTION_IF GAME_IS ~iwdee~ BEGIN
// BGEE
COPY  ~Eldritch_Magic/Effects/emlaw.eff~   ~override~
COPY ~Eldritch_Magic/ITM/emsw1h05.itm~ ~override~ // Silver Long Sword +2
  SAY NAME1 ~~
  SAY NAME2 @102
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @103
COPY ~Eldritch_Magic/ITM/emsw1h06.itm~ ~override~ // Flaming Burst Long Sword +1
  SAY NAME1 ~~
  SAY NAME2 @104
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @105
COPY ~Eldritch_Magic/ITM/emsw1h07.itm~ ~override~ // Frost-Fire Long Sword +2
  SAY NAME1 ~~
  SAY NAME2 @106
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @107
COPY ~Eldritch_Magic/ITM/emsw1h10.itm~ ~override~ // Mithral Long Sword +3
  SAY NAME1 ~~
  SAY NAME2 @108
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @109
COPY ~Eldritch_Magic/ITM/emsw1h02.itm~ ~override~ // Adamantine Long Sword of Biting +1
  SAY NAME1 ~~
  SAY NAME2 @110
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @111
COPY ~Eldritch_Magic/ITM/emsw1h12.itm~ ~override~ // Vampiric Short Sword +1
  SAY NAME1 ~~
  SAY NAME2 @112
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @113
COPY ~Eldritch_Magic/ITM/emsw1h03.itm~ ~override~ // Masterwork Cold Iron Long Sword
  SAY NAME1 ~~
  SAY NAME2 @114
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @115
COPY ~Eldritch_Magic/ITM/emsw1h13.itm~ ~override~ // Elemental Long Sword +1
  SAY NAME1 ~~
  SAY NAME2 @116
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @117
COPY ~Eldritch_Magic/ITM/emsw1h09.itm~ ~override~ // Holy Avenger Long Sword +3
  SAY NAME1 ~~
  SAY NAME2 @118
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @119
COPY ~Eldritch_Magic/ITM/embhaal.itm~ ~override~ // Bhaal's Holy Symbol
  SAY NAME1 ~~
  SAY NAME2 @120
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @121
COPY ~Eldritch_Magic/ITM/emchanco.itm~ ~override~ // Elven Chain Mail of the Collector
  SAY NAME1 ~~
  SAY NAME2 @140
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @141
// BG2EE
COPY ~Eldritch_Magic/Creatures/Sar1L.BMP~ ~override/Sar1L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar2L.BMP~ ~override/Sar2L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar1L.BMP~ ~portraits~
COPY ~Eldritch_Magic/Creatures/Sar2L.BMP~ ~portraits~
COPY ~Eldritch_Magic/Creatures/Sar1M.BMP~ ~override/Sar1L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar2M.BMP~ ~override/Sar2L.BMP~
COPY ~Eldritch_Magic/Creatures/Sar1M.BMP~ ~portraits~
COPY ~Eldritch_Magic/Creatures/Sar2M.BMP~ ~portraits~
COPY  ~Eldritch_Magic/Spells/emcdcha.spl~   ~override~
      SAY 0xfe @219 //You feel a tug from the Pocket Plane as an artifact lost to time materializes among your possessions. Surely such a happening is linked to your powerful heritage.
COPY  ~Eldritch_Magic/Spells/emcdbls.spl~   ~override~
      SAY 0x15e @213 //You have been acknowledged by the Bladesinger's Guild.
COPY  ~Eldritch_Magic/Spells/emcdsw1.spl~   ~override~
      SAY 0xfe @214 //You are an exemplary Bladesinger and a hero among elves. The Gods themselves have taken notice of your righteous fury and now the Seldarine have blessed you with the tool to exact it. Be advised not to abuse a divine gift.
COPY  ~Eldritch_Magic/Effects/emundead.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emdemon.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh1.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh2.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/emhugh3.eff~   ~override~
COPY  ~Eldritch_Magic/Effects/em2d6.eff~   ~override~
COPY  ~Eldritch_Magic/Dialog/emsw1h01.dlg~   ~override~
      SAY 0x34  @200 //(The sword flashes for a moment, then permeates your mind with melodic Elven whispers.)
      SAY 0x44  @201 // ...
      SAY 0x54  @202 // "I am as I have always been."
      SAY 0x64  @204 //(The sword emits a shockingly demi-human sigh) "42."
      SAY 0x74  @206 //(The sword is silent a moment.) "That would have to be a hectaoncheire, 'hundredhanded one' - a few Gods fell that day. Pray you never face one, much less two."
      SAY 0x84  @208 // "I may be a holy artifact forged by the Gods, but I'm still a sword. Aren't there any evil Bhaalspawn left?"
      SAY 0x98  @198 // Never mind. Let's just continue on for now.
      SAY 0xb8  @199 // What's your status, sword?
      SAY 0xd8  @203 // What is the answer to life, the universe, and everything?
      SAY 0xf8  @205 // What's the most powerful foe you've vanquished?
      SAY 0x118 @207 // What would you have me do, O Sentient Sword?
COPY  ~Eldritch_Magic/Spells/emsare1.spl~   ~override~
      SAY 0xce @94 //Blades
COPY  ~Eldritch_Magic/Spells/emsare2.spl~   ~override~
      SAY 0xce @95 //Spikes
COPY_EXISTING ~lunumab.2da~ ~override~
  APPEND ITEMDIAL.2da ~EMSW1H01      5689   EMSW1H01~
COPY_EXISTING ~item_use.2da~ ~override~
  APPEND item_use.2da ~emplat01   SAREVOK    9382       2~
  APPEND item_use.2da ~emsw2h01   SAREVOK    9382       2~
  APPEND item_use.2da ~emsarev   SAREVOK    9382       2~
COPY ~Eldritch_Magic/ITM/emboot01.itm~ ~override~ // Elven Boots of Speed: The Paws of the Lythari
  SAY NAME1 @26
  SAY NAME2 @27
  SAY UNIDENTIFIED_DESC @28
  SAY DESC @29
  SAY 0x15e @96 // Bladesinger
COPY ~Eldritch_Magic/ITM/emchan01.itm~ ~override~ // Holy Elven Chain +6
  SAY NAME1 @30
  SAY NAME2 @31
  SAY UNIDENTIFIED_DESC @32
  SAY DESC @33
  SAY 0x3fe @96
COPY ~Eldritch_Magic/ITM/emclck01.itm~ ~override~ // Bladesinger's Shroud
  SAY NAME1 @34
  SAY NAME2 @35
  SAY UNIDENTIFIED_DESC @36
  SAY DESC @37
  SAY 0x2b6 @96
COPY ~Eldritch_Magic/ITM/emring01.itm~ ~override~ // Bladesinger's Signet
  SAY NAME1 @38
  SAY NAME2 @39
  SAY UNIDENTIFIED_DESC @40
  SAY DESC @41
  SAY 0x2de @96
COPY ~Eldritch_Magic/BAM/emsw1h01.bam~ ~override~
COPY ~Eldritch_Magic/ITM/emsw1h01.itm~ ~override~// Seldarine's Fury +6: Shame of the Gods
  SAY NAME1 @42
  SAY NAME2 @43
  SAY UNIDENTIFIED_DESC @44
  SAY DESC @45
  SAY 0x586 @96
COPY ~Eldritch_Magic/ITM/emsw1h11.itm~ ~override~ // Angharradh's Song
  SAY NAME1 ~~
  SAY NAME2 @47
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @49
  SAY 0x1f6 @96
COPY ~Eldritch_Magic/ITM/embelt25.itm~ ~override~ // Girdle of Titan Strength
  SAY NAME1 ~~
  SAY NAME2 @58
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @59
COPY ~Eldritch_Magic/ITM/emthay.itm~ ~override~ // Red Robe of Thay
  SAY NAME1 ~~
  SAY NAME2 @60
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @61
  SAY 0x36e @97 // Red Wizard of Thay
COPY ~Eldritch_Magic/ITM/emsw1h04.itm~ ~override~ // Blue Flame Taragarth +3
  SAY NAME1 ~~
  SAY NAME2 @62
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @63
COPY ~Eldritch_Magic/ITM/emdagg01.itm~ ~override~ // Netherese Spellblade
  SAY NAME1 ~~
  SAY NAME2 @64
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @65
COPY ~Eldritch_Magic/ITM/emsw1h08.itm~ ~override~ // Plasma Blade of Kossuth: Igneus Nova
  SAY NAME1 ~~
  SAY NAME2 @66
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @67
COPY ~Eldritch_Magic/BAM/phelm29.bmp~ ~override~
COPY ~Eldritch_Magic/ITM/empsion.itm~ ~override~ // Drow Psionicist's Cowl
  SAY NAME1 ~~
  SAY NAME2 @68
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @69
COPY ~Eldritch_Magic/ITM/emveye.itm~ ~override~ // Eye of Vecna
  SAY NAME1 ~~
  SAY NAME2 @70
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @71
COPY ~Eldritch_Magic/ITM/emvhand.itm~ ~override~ // Hand of Vecna
  SAY NAME1 ~~
  SAY NAME2 @72
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @73
COPY ~Eldritch_Magic/ITM/emimoen.itm~ ~override~ // Imoen's Belt
  SAY NAME1 ~~
  SAY NAME2 @52
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @53
  SAY 0x2de @98 // IMOEN
COPY ~Eldritch_Magic/ITM/emplat01.itm~ ~override~ // Sarevok's Bladed Armor +5
  SAY NAME1 ~~
  SAY NAME2 @54
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @55
COPY ~Eldritch_Magic/ITM/emsw2h01.itm~ ~override~ // Sword of Chaos +5
  SAY NAME1 ~~
  SAY NAME2 @56
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @57
COPY ~Eldritch_Magic/ITM/emsarev.itm~ ~override~ // Sword of Chaos +5 (Ascension)
  SAY NAME1 ~~
  SAY NAME2 @56
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @57
COPY ~Eldritch_Magic/ITM/emheart.itm~ ~override~ // Black Heart of Kazgaroth
  SAY NAME1 ~~
  SAY NAME2 @220
  SAY UNIDENTIFIED_DESC ~~
  SAY DESC @221
COPY ~Eldritch_Magic/ITM/emhugh.itm~ ~override~ // Sword of Cymrych Hugh
  SAY NAME1 @42
  SAY NAME2 @255
  SAY UNIDENTIFIED_DESC @44
  SAY DESC @256
  SAY 0x19e @224
  SAY 0x1ce @224
  SAY 0x1fe @224
COPY ~Eldritch_Magic/ITM/emhide.itm~ ~override~ // Kazgaroth's Hide
  SAY NAME1 @225
  SAY NAME2 @222
  SAY UNIDENTIFIED_DESC @226
  SAY DESC @223
  SAY 0x22e @224
 PRINT ~“He who fights with monsters should look to it that he himself does not become a monster . . . when you gaze long into the abyss the abyss also gazes into you”
- Friedrich Nietzsche~
END